/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4SivZ3Jc2UgLpQWScIp3wW+1FXNG9hkwI6jdNxiJ/CDvJro5kDR6kawmCkUEWBMIaCxgbz4PP/bT6K+giOnzLA==
 */

// eslint:disable
// tslint:disable

interface SnesPunks {
  id: number & {readonly __brand?: 'snes_punks_id'}
  traits: any
}
export default SnesPunks;

interface SnesPunks_InsertParameters {
  id: number & {readonly __brand?: 'snes_punks_id'}
  traits: any
}
export type {SnesPunks_InsertParameters}
